# Set max line length before warning (default is 120)
line_length: 245

disabled_rules:
  - identifier_name # Disables SwiftLint complaining about enums with associated values
  - trailing_whitespace # Disables SwiftLint complaining about whitespace characters on empty lines

excluded:
  - Pods
