# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
env:
  global:
    - WORKSPACE=SessionTools.xcworkspace
    - IOS_FRAMEWORK_SCHEME="SessionTools-iOS"
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=11.3,name=iPhone X" SDK="iphonesimulator" SCHEME="$IOS_FRAMEWORK_SCHEME" RUN_TESTS="YES" POD_LINT="YES"  RUN_DANGER="YES"
addons:
  homebrew:
    update: true
    taps:
      - danger/tap
    packages:
      - danger-swift
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install
script:
  - set -o pipefail

  # Build Framework and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -enableCodeCoverage YES -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO | xcpretty;
    else
      xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --allow-warnings;
    fi

  # Run Danger if specified
  - if [ $RUN_DANGER == "YES" ]; then
      DEBUG='*' danger-swift ci;
    fi
# after_success:
 # - bash <(curl -s https://codecov.io/bash)

# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
